#!/bin/bash

docker buildx create \
--name multiarch \
--driver docker-container \
--platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x \
--bootstrap \
--use

docker buildx build \
--platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x \
--progress plain \
-f $DOCKERFILE_PATH \
-t $IMAGE_NAME \
--push \
.

echo "** push of multiarch build completed ---- displaying output of docker buildx imagetools inspect $IMAGE_NAME :"
docker buildx imagetools inspect $IMAGE_NAME
