#!/bin/bash

docker buildx create \
--name multiarch \
--driver docker-container \
--platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x \
--bootstrap \
--use

echo "attempt to build IMAGE_NAME $IMAGE_NAME tag $DOCKER_TAG repo $DOCKER_REPO"

docker buildx build \
--platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x \
--pull \
--progress plain \
--tag $IMAGE_NAME:latest \
--file $DOCKERFILE_PATH \
--push \
.

